#!/bin/bash

# Print help message.
function usage() {
	echo """spotiPy launcher
  run             Run spotiPy CLI
  credentials     Set credentials
  install         Install venv with dependencies and proccess credentials
  docker_mode     Same as run, but whie in dokcer
  help            Print this help
  """
}

# Set user credentials.
function credentials() {
	echo "[!] Provide Spotify crendetials"

	# Check for existing file.
	if [ -f credentials ]; then
		echo "[!] File with credentials already exists"
		read -p "[?] Overwrite? [y/n] " decision

		if [ "$decision" = "y" ]; then
			>credentials
		else
			echo "[!] Aborted"
			exit 1
		fi
	else
		touch credentials
	fi

	for value in USERID KEY SECRET; do
		read -p "[>] $value: " temp
		echo "$value=$temp" >>credentials
	done
	echo "[!] Credentials saved"
}

# Setup Python enviroment and install dependencies.
function install() {
	echo "[!] Creating virtual enviroment"
	cd spotipy_env
	python3 -m venv .

	echo "[!] Installing dependencies"
	source bin/activate
	python -m ensurepip
	pip install -r ../requirement.txt
	pip install --upgrade spotdl
	deactivate
	cd ..
}

# Check for updates and run script.
function run() {
	echo "[!] Checking for updates"
	git pull

	echo "[!] Running virtual enviroment"
	source spotipy_env/bin/activate
	python -m spotipy_env
	echo "[!] Exiting virtual enviroment"
	deactivate
}

function run_in_docker() {
	if [ ! -f credentials ]; then
		credentials
	fi
	python -m spotipy_env
}

if [ "$1" == "run" ]; then
	run
elif [ "$1" == "credentials" ]; then
	credentials
elif [ "$1" == "install" ]; then
	install
	credentials
elif [ "$1" == "docker_mode" ]; then
	run_in_docker
else
	usage
fi
